name: CI devops 2024
on:
  #to begin you want to launch this job in main and develop
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      #checkout your github code using actions/checkout@v2.5.0
      - uses: actions/checkout@v2.5.0

      #do the same with another action (actions/setup-java@v3) that enable to setup jdk 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      #finally build your app with the latest command
      - name: Build and test with Maven
        run : mvn clean verify -f simple-api/pom.xml

      - name: SonarCloud Scan
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Your SonarCloud token
        run: mvn sonar:sonar -Dsonar.projectKey=tintamarr_DockerTP2 -Dsonar.organization=tintamarr -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -f simple-api/pom.xml


  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PWD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build image and push backend
      - name: Build image and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./simple-api
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/master' }}
      # Build image and push database
      - name: Build image and push database
        uses: docker/build-push-action@v3
        with:
          context: ./database  # Assurez-vous que le chemin est correct
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/master' }}
      # Build image and push httpd
      - name: Build image and push httpd
        uses: docker/build-push-action@v3
        with:
          context: ./http-server # Assurez-vous que le chemin est correct
          tags: ${{ secrets.DOCKER_USERNAME }}/tp-devops-httpd:latest
          push: ${{ github.ref == 'refs/heads/master' }}