name: Test Backend

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2.5.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build and test with Maven
        run: mvn clean verify -f simple-api/pom.xml

      - name: SonarCloud Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided by GitHub
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Your SonarCloud token
        run: mvn sonar:sonar -Dsonar.projectKey=tintamarr_DockerTP2 -Dsonar.organization=tintamarr -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }} -f simple-api/pom.xml
